name: 'Test'

on:
  pull_request:

jobs:
  test:
    name: Run devenv tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Run devenv tests
        run: nix flake check
