name: 'Test'

on:
  pull_request:

jobs:
  test:
    name: Run devenv tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Run devenv tests
        shell: 'script -q -e -c "bash {0}"'
        run: devenv test
