name: 'publish images'

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build images with Nix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [psql, pgcli, usql]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - uses: cachix/install-nix-action@v30
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build
        run: |
          nix build '.#${{ matrix.app }}-image'
          docker load < result
      - name: Push image
        if: github.event_name != 'pull_request'
        run: |
          docker push kyokley/${{ matrix.app }}
